#!/usr/bin/env bash

# since sierra the ssh-agent doesn't behave like the same as before .. for security and OpenSSH compliant issues
# https://openradar.appspot.com/27348363
[ -z "$(C= ssh-add -l | grep -v 'The agent has no identities')" ] && ssh-add -A
