#!/usr/bin/env bash
loadBashCompletions() {
    local bc_cmd="/opt/local/etc/bash_completion"
    local bc_extension

    if [ -f "$(which brew)" ]; then
        local bc_cmd_brew=$(brew --prefix)"/etc/bash_completion"
        if [ -f "$bc_cmd_brew" ]; then
            bc_cmd=$bc_cmd_brew
        fi
    fi

    if [ -f "$bc_cmd" ]; then
        . ~/.bashrc.d/helper/sourceCompletions.sh "bash_completion" $bc_cmd
    else
        echo -e $RED"--- bash_completion missing"$NO_COLOR
        return 1
    fi

    [ -d ~/.bashrc.d/__${BASH_SOURCE##*/} ] && for bc_extension in ~/.bashrc.d/__${BASH_SOURCE##*/}/*; do . ~/.bashrc.d/helper/sourceCompletions.sh "__bash_completion_extension_$(basename $bc_extension)" ${bc_extension}; done
}
loadBashCompletions