#!/usr/bin/env bash
export PROMPT_COMMAND_OS="${PROMPT_COMMAND_OS:-${PROMPT_COMMAND}}"
export PROMPT_COMMAND="my_prompt"

export PS0="$0:$"
export PS1="\[\033[1;37m\]$0:[\$(date +%F\" \"%H:%M:%S\ @%s)] \[\033[1;32m\]\u\[\033[0m\]@\h\n$0:"$(if [ "$EUID" -eq 0 ]; then echo "#"; else echo "$"; fi)" "
