#!/usr/bin/env bash
function mkdir
{
    [ -n "${DEBUG}" ] && echo "v.0.2" 1>&2;
    [ -n "${DEBUG}" ] && echo "childNo.de" 1>&2;
	
    /usr/bin/env mkdir "$@"
    mkExitCode=$?

	# quit if on error or not interactive
	[[ ${mkExitCode} != 0 || $- != *i* ]] && return ${mkExitCode}

    for mkdnewdir in "$@"; do
        if [ -d "${mkdnewdir}" ]; then
            read -p "change to new directory '${mkdnewdir}'? [Y/n] ";
            if [ "$REPLY" == "n" -o "$REPLY" == "N" -o "$REPLY" == "NO" -o "$REPLY" == "no" ]; then
                continue;
            fi
            cd "${mkdnewdir}";
            return $mkExitCode;
        fi
    done
	unset mkdnewdir
	
    return ${mkExitCode};
	# TODO: check how to unset
	unset mkExitCode
}
