#!/usr/bin/env bash
# enable bash completion in interactive shells
loadBashCompletions() {
    local bc_cmd
    local bc_extension
    if ! shopt -oq posix; then
      if [ -f /usr/share/bash-completion/bash_completion ]; then
        bc_cmd=/usr/share/bash-completion/bash_completion
      elif [ -f /etc/bash_completion ]; then
        bc_cmd=/etc/bash_completion
      fi
    fi

    if [ -f "$bc_cmd" ]; then
        . ~/.bashrc.d/helper/sourceCompletions.sh "bash_completion" $bc_cmd
    else
        echo -e $RED"--- bash_completion missing"$NO_COLOR
        return 1
    fi

    [ -d ~/.bashrc.d/__${BASH_SOURCE##*/} ] && for bc_extension in ~/.bashrc.d/__${BASH_SOURCE##*/}/*; do . ~/.bashrc.d/helper/sourceCompletions.sh "__bash_completion_extension_$(basename $bc_extension)" ${bc_extension}; done
}
loadBashCompletions